Feature/primera entrega
anasolcentur/Programacion_Web_I pull request #1
Opened 2024-09-15 22:08 UTC by anasolcentur

Pull Request de la primera entrega.

2024-09-15 23:11 UTC, MVelasquez98 commented
Hola Ana Sol,
¿cambiaste de repositorio?¿Borraste mis correcciones?¿recreaste la pr?
Tene en cuenta que tenes que usar el mismo repositorio donde te hice las correcciones, corregir los cambios en la rama "feature/primera-entrega" y hacer los commits correspondientes, para poder aprobar esa PR donde te hice las correcciones.
Sino no tengo manera de saber si hiciste los cambios que te pedi.

2024-09-15 23:21 UTC, anasolcentur commented
@MVelasquez98 Hola profe.
Si, tuve que eliminar el repositorio y volver a hacerlo porque tenia errores en la manera en la que lo cree y no sabia como modificarlos. 
Había creado la rama main en lugar de master. 
Tenia problemas para que se visualice el archivo index.html en el GitHub pages (Se abría el read.me nomas)
Me había olvidado de cargar las imágenes necesarias para la pagina.
Y dentro del código no tenia ningún error en particular solo que ya había agregado el espacio para desarrollar la parte de java y usted me recomendó borrarlo para no tener problemas.

Sinceramente se me había complicado mucho la parte de vincular todo al GitHub y estaba medio perdida por lo que consideré mejor volver a empezarlo.

2024-09-15 23:25 UTC, MVelasquez98 commented
Entiendo, para la próxima consultame, porque el seguimiento del resto de entregas va ser sobre los comentarios que hago en las pull request a modo de code-review. Sino no tengo manera de saber si vas avanzando o no.

2024-09-15 23:26 UTC, MVelasquez98 requested changes
Las imagenes deben estar dentro de una carpeta "img" o "assets". Solo el index.html en la raiz.

2024-09-16 21:04 UTC, anasolcentur commented
@MVelasquez98 Ya cree la carpeta img y moví las imágenes ahi.

2024-09-16 23:02 UTC, MVelasquez98 approved these changes
LGTM

2024-09-16 23:32 UTC, merged