Release/primer parcial
anasolcentur/Programacion_Web_I pull request #3
Opened 2024-10-04 02:05 UTC by anasolcentur

2024-10-04 17:58 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

**Incorporación de Componentes Avanzados de HTML (1 punto):**

- ⚠️ Agregar al menos un componente avanzado de HTML a la página, como un iframe de un video de YouTube o un mapa de Google Maps. (1 punto). El video incrustado no se visualiza. 

**Implementación de Bootstrap para Diseño Responsivo (5 puntos):**

- ✅ Instalar la biblioteca Bootstrap en el proyecto. (1 punto)
-  ⚠️ Utilizar el sistema de columnas de Bootstrap para hacer que el sitio sea más responsivo en dispositivos móviles. (3 puntos). Podría aprovecharse mejor el [sistema de columnas en Bootstrap](https://getbootstrap.esdocu.com/docs/5.1/layout/columns/) o [grilla](https://getbootstrap.com/docs/4.0/layout/grid/) para mejorar el [Diseño UI](https://perio.unlp.edu.ar/catedras/comyddhhlic/wp-content/uploads/sites/125/2023/02/Diseno-UX-UI.pdf), más que nada en dispositivos moviles. 
- ✅Incluir al menos un componente avanzado de Bootstrap, como un carrusel, una barra de navegación o un modal. (1 punto)

**Gestión del Proyecto con GitHub (4 puntos):**

- ✅ Realización de commits necesarios sobre la rama de desarrollo utilizando Git. (1 punto)
- ⚠️ Creación de una rama "release/primer-parcial" a partir de la rama "develop" utilizando Git. (1 punto) Vas a tener que resolver los [conflictos de merge](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line) para la próxima entrega.
-  ✅ Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/segunda-entrega" con "develop" en GitHub. (1 punto)
-  ✅ Proporcionar la URL de la pull request y la URL generada por GitHub Pages para la rama "release/primer-parcial" como parte de la entrega. (1 punto)

**Nota:** 7 (Siete)

2024-10-04 17:58 UTC, MVelasquez98 commented on index.html
> +    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
Si vas a poner el script al principio del archivo tenes que agregar el atributo **[defer](https://www.w3schools.com/tags/att_script_defer.asp)** al final, sino solamente pones el script al final de todo dentro del body. Esto para evitar errores asyncronicos a futuro.

2024-10-04 17:58 UTC, MVelasquez98 commented on index.html
> +                        <img src="img/Sweater_2.jpeg" class="d-block w-100" alt="Sweater Molly">
¿Es el comportamiento esperado que las imagenes ocupen el ancho total? Pregunto a nivel UI, UX.
Fijate como se ve en dispositivos moviles desde el inspector
![image](https://github.com/user-attachments/assets/6b3c7454-0db8-4eaf-91af-2654889eb140)

2024-10-04 17:58 UTC, MVelasquez98 commented on index.html
> +                <iframe width="560" height="315" src="https://www.youtube.com/embed/Crochet%20Cardigan%20%7C%20Crochet%20Sweater%20Tutorial" frameborder="0" allowfullscreen></iframe>
Parece que YouTube bloqueo el video que incrustaste
![image](https://github.com/user-attachments/assets/aca2a72e-3bb4-4caf-bdf3-30a8e6ad9019)

2024-10-21 19:11 UTC, anasolcentur commented
Realice las correcciones correspondientes del primer parcial.
@MVelasquez98

2024-10-21 19:27 UTC, MVelasquez98 commented
@anasolcentur Dos cosas solamente:
- Tenes [conflictos de merge por resolver](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) (no te va dejar hacer merge commit hasta que los resuelvas):
![image](https://github.com/user-attachments/assets/c35f3454-84d4-4ca6-b514-f990d18a7d9f)
Eso es normal, porque encuentra diferencias grandes entre los dos archivos: el que esta actualmente es master desactualizado desde que se creo la rama inicialmente, y el readme actualizado en el parcial. Solo tenes que indicarle qu tome los cambios de tu parcial.

- Lo otro es más un detalle que podes resolver incluso durante la tercera entrega. El navbar no se ve responsivo en los dispositivos moviles:
![image](https://github.com/user-attachments/assets/5ba24f83-dbaa-4700-9472-84c567bfb303)
Podes hacer uso del [componente NavBar de Bootstrap](https://getbootstrap.com/docs/4.0/components/navbar/) para resolverlo:
![image](https://github.com/user-attachments/assets/d47ee342-f348-4726-9adb-fd0a5aa1eff7)

2024-10-21 20:56 UTC, anasolcentur commented
Ya agregue los cambios de la Navbar. Pero no se si ya se soluciono el conflicto de merge. 
@MVelasquez98

2024-10-22 03:02 UTC, MVelasquez98 approved these changes
LGTM

2024-10-22 22:19 UTC, merged