Feature/tercera entrega
anasolcentur/Programacion_Web_I pull request #5
Opened 2024-10-22 22:42 UTC by anasolcentur

2024-10-23 14:46 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Algoritmos (1 punto)**
❌  0 puntos: Uso incorrecto o ineficiente de algoritmos condicionales y ciclos. No estas usando ningún ciclo (for, while, do-while)

- **Funciones (1 punto)**
✅ 1 punto: Funciones con nombres claros, estructura correcta y resultados correctos.

- **Funcionalidad (1 punto)**
❌  0 puntos: Flujo de trabajo incompleto o funcionalidad inapropiada al contexto. Tu algoritmo no resuelve nada funcional para la pagina, solo hay una validación de un nombre y una validación de formulario (que utiliza eventos y DOM que no vimos en la unidad y no entra en esta entrega). Se espera algun algoritmo relacionado con calcular un precio, filtrar o buscar productos, armar un carrito de compras, etc.

- **Interactividad (1 punto)**
⚠️ 0.5 puntos: Interactividad insuficiente o salidas incoherentes. Hay un solo prompt pidiendo el nombre, el resto de entradas son con DOM, que no entra en esta entrega.

- **Escalabilidad (1 punto)**
❌ 0 puntos: Falta de funciones con parámetros, arrays o objetos relevantes. No utilizas clases ni métodos.

- **Legibilidad (1 punto)**
⚠️ 0.5 puntos: Nombres de variables, funciones u objetos poco significativos, código ilegible o mal estructurado. No hace falta invocar al evento de load para llamar a la funcion `capturarNombre()`, con solo llamarla en el root del archivo basta.

**GitHub (4 puntos):**
- ✅ 1 punto: Creación de una rama "backport/primer-parcial" a partir de la rama "master" utilizando Git.
- ✅ 1 punto: Creación de una rama "feature/tercera-entrega" a partir de la rama "develop" utilizando Git.
- ✅ 1 punto: Correcta realización de la solicitud de revisión para fusionar la rama "backport/primer-parcial" con "develop" en GitHub, resolviendo los conflictos de merge (si fuese necesario).
- ✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "release/primer-parcial" con "master" en GitHub,  resolviendo los conflictos de merge (si fuese necesario).

2024-11-19 21:34 UTC, anasolcentur commented
Correcciones realizadas. @MVelasquez98

2024-11-20 00:51 UTC, MVelasquez98 commented
Te falta sacar el manejo de DOM y Eventos para esta entrega, te recomiendo guardar todo este desarrollo, porque es lo que justamente es en parte la cuarta entrega

2024-11-20 01:08 UTC, anasolcentur commented
@MVelasquez98

2024-11-25 21:37 UTC, anasolcentur commented
@MVelasquez98

2024-11-26 02:14 UTC, MVelasquez98 commented
Revisar comentarios

2024-11-27 00:41 UTC, anasolcentur commented
@MVelasquez98

2024-11-27 00:55 UTC, MVelasquez98 commented
¿Llegaste a ver estos comentarios?
![image](https://github.com/user-attachments/assets/e2581b70-ffed-4396-a012-92c1a1f78a65)
![image](https://github.com/user-attachments/assets/8e58fbcf-e7cd-49e1-84d9-0ec6a9cf57bd)
![image](https://github.com/user-attachments/assets/720c9d32-a78d-4cb1-9749-bf502d0adccc)

Siempre revisa en [files changed](https://github.com/anasolcentur/Programacion_Web_I/pull/5/files) que no tengas ningun comentario en pending.

Si ves este simbolo en la pr, significa que seguis teniendo comentarios pendientes por resolver.
![image](https://github.com/user-attachments/assets/03bd5080-48a1-4c45-a9e5-72c9bd9e1a39)

2024-11-27 23:06 UTC, anasolcentur commented
@MVelasquez98 
Hola profe, ahi realice las correcciones que me mando captura, pero esos comentarios no me aparecen en ningún lado o yo nose como visualizarlos. La pr me sigue marcando como que tengo un comentario pendiente por resolver pero ya no se que se supone que tengo que modificar.

2024-11-28 02:50 UTC, MVelasquez98 approved these changes
LGMT
Podes pensar en una clase Producto que contenga estas propiedades, entonces haces un array de instancias de la clase producto, pensalo para la cuarta entrega el cambio

2024-11-28 02:50 UTC, MVelasquez98 commented on script.js
> +    const nombre = document.getElementById('nombre').value;
No entra en esta entrega el uso de DOM, estos son los unicos temas de la unidad:
![image](https://github.com/user-attachments/assets/b63fc739-6b00-4bde-8243-0d2929c1af35)
⚠️ Cuidado con el [feature creep](https://www.agile-academy.com/en/agile-dictionary/feature-creep/)

2024-11-28 02:50 UTC, MVelasquez98 commented on script.js
> +document.addEventListener('DOMContentLoaded', () => {
No entra en esta entrega el uso de Eventos, estos son los unicos temas de la unidad:
![image](https://github.com/user-attachments/assets/b63fc739-6b00-4bde-8243-0d2929c1af35)
⚠️ Cuidado con el [feature creep](https://www.agile-academy.com/en/agile-dictionary/feature-creep/)

2024-11-28 02:50 UTC, MVelasquez98 commented on script.js
> +document.querySelectorAll('.agregar-carrito').forEach(button => {
En esta tercera entrega no entra uso de DOM, eso es en la cuarta entrega.
Aca solo es entrada de datos con prompt

2024-11-28 02:50 UTC, MVelasquez98 commented on script.js
> +const carritoCantidad = document.getElementById('carritoCantidad');
No entra DOM

2024-11-28 02:50 UTC, MVelasquez98 commented on script.js
> +    button.addEventListener('click', function() {
No entran en el manejo de eventos en esta entrega, eso es en la cuarta entrega

2024-11-28 02:50 UTC, MVelasquez98 commented on script.js
> +        const div = document.createElement('div');
No entra DOM

2024-11-28 02:50 UTC, MVelasquez98 commented on script.js
> +let carrito = {
Esto tiene que estar definido en una clase Carrito.js en un archivo aparte, y exportar e importar la clase para su uso, tal como hicimos en el [encuentro](https://github.com/MVelasquez98/Programaci-n-Web-I---UCES/tree/feature/tercera-entrega/Clase%2009)

2024-11-28 02:50 UTC, MVelasquez98 commented on script.js
> +    carrito.mostrarCarrito();
Recorda la simulación tiene que ser :
entrada - proceso - salida
Te falta la entrada de datos con [prompt](https://developer.mozilla.org/es/docs/Web/API/Window/prompt) en esta entrega

2024-11-28 02:50 UTC, MVelasquez98 commented on index.html
>              <form action="enviar_mensaje.php" method="post">
No corresponde el enviar_mensaje.php, no vamos a usar este lenguaje en la materia. Simplemente no pongas el action

2024-11-28 02:50 UTC, MVelasquez98 commented on script.js
> +    { nombre: "Sweater Rainbow", precio: 15000, cantidad: 10 },
Podes pensar en una clase Producto que contenga estas propiedades, entonces haces un array de instancias de la clase producto

2024-11-28 15:48 UTC, merged