Implementacion de las consignas de la Actividad 4.
anasolcentur/Programacion_Web_I pull request #6
Opened 2024-11-28 16:52 UTC by anasolcentur

Ahi agregue los cambios de la actividad 4.
@MVelasquez98

2024-11-28 17:01 UTC, MVelasquez98 commented
No hiciste deploy de esta branch en GithubPages para ver los cambios

2024-11-28 17:14 UTC, anasolcentur commented
@MVelasquez98 
Ahi hice deploy de esta branch en GithubPages.

2024-11-28 18:35 UTC, MVelasquez98 requested changes

2024-11-28 18:35 UTC, MVelasquez98 commented on script.js
> +    mensajeCompra.textContent = 'Gracias por tu compra!';
No se termina de apreciar que paso con la compra cuando finaliza, podes incluso usar [modales](https://getbootstrap.com/docs/4.1/components/modal/), o hasta animarte a usar alguna lib de js como [SweetAlert](https://sweetalert2.github.io/)

2024-11-28 18:35 UTC, MVelasquez98 commented on script.js
> +
En la interacción de usuario nunca queda claro que esta pasando cuando agregas un producto al carrito,  podes incluso usar [modales](https://getbootstrap.com/docs/4.1/components/modal/), o hasta animarte a usar alguna lib de js como [Toastify](https://apvarun.github.io/toastify-js)

2024-11-28 18:35 UTC, MVelasquez98 commented on script.js
> -let carrito = new Carrito();
¿Por que eliminas el uso de la clase carrito? Tenes que usar esto

2024-11-28 18:35 UTC, MVelasquez98 commented on script.js
> -let productos = [
¿Por que eliminas el uso de arrays? Tenes que usar arrays

2024-11-28 18:35 UTC, MVelasquez98 commented on carrito.js
> +export class Carrito {
Nunca usas esta clase Carrito

2024-11-28 18:35 UTC, MVelasquez98 commented on script.js
> +    button.addEventListener('click', function() {
Todo lo que viene a continuación, ¿no es lo que haria `carrito.agregarProducto(producto)`?¿Cuando usas la clase Carrito.js?

2024-11-28 18:35 UTC, MVelasquez98 commented on script.js
> +function actualizarCarrito() {
Todo lo que viene a continuación, ¿no es lo que haria` carrito.actualizarCarrito()`?¿Cuando usas la clase Carrito.js?

2024-11-28 18:35 UTC, MVelasquez98 commented on script.js
> +    carritoSection.style.display = 'none';
Estilos dinámicos: Usa clases CSS para mostrar/ocultar el carrito en lugar de manipular directamente style.display. Esto mejora la mantenibilidad, por ejemplo:
carrito.classList.toggle("visible");

2024-11-28 18:35 UTC, MVelasquez98 commented on script.js
> +    carritoSection.style.display = 'block';
Estilos dinámicos: Usa clases CSS para mostrar/ocultar el carrito en lugar de manipular directamente style.display. Esto mejora la mantenibilidad, por ejemplo:
`carrito.classList.toggle("visible");`

2024-11-28 18:35 UTC, MVelasquez98 commented on index.html
> +                            <a class="nav-link custom-nav-link" href="#" id="verCarrito">Ver Carrito <span id="carritoCantidad">0</span></a>
Cuando hago click en este boton estaria bueno que me muestre donde esta el carrito, sino parece un boton sin funcionalidad, y como usuario no entiendo que esta pasando

2024-11-28 18:37 UTC, MVelasquez98 commented
¿Ves esto? 
![image](https://github.com/user-attachments/assets/31272415-c417-48d2-9303-b7ed814ba031)
Si haces click en [view review changes](https://github.com/anasolcentur/Programacion_Web_I/pull/6/files/91ea5553dba101221d7dfd986ab5af92a82bdabd), te lleva aca
![image](https://github.com/user-attachments/assets/3448c4c5-7516-4946-9ba9-f1701e191553)Aca no vas a ver nada hasta que recorras hasta abajo todo el archivo en busca de comentarios en cada linea de codigo:
![image](https://github.com/user-attachments/assets/e311ba75-211a-4866-9796-d978652c0bdf)
Una vez que ya resolviste un comentario le das "resolve conversation"
![image](https://github.com/user-attachments/assets/e278f462-768b-4c9f-bc49-c972851b0a29)

2024-11-28 21:44 UTC, MVelasquez98 commented
Error en consola, revisa los import y export:
![image](https://github.com/user-attachments/assets/d3f57948-5edf-4dcd-9595-29bd42a3cd1f)

2024-11-28 22:39 UTC, anasolcentur commented
![2024-11-28_19-32-49](https://github.com/user-attachments/assets/e0e5a4a4-d63d-46c2-a4af-7f14e1ce1baf)

Por alguna razon me aparece así en el git, por eso no debe funcionar. Como lo tendría que arreglar? Desde el archivo en mi maquina se visualiza todo bien.

2024-11-28 22:44 UTC, MVelasquez98 commented
Cambiaste el nombre o creaste dos archivos diferentes
<img width="228" alt="image" src="https://github.com/user-attachments/assets/492e6bf4-0ff1-49cd-be80-8bba0d80ce41">
es "Carrito" con PascalCase no "carrito"

2024-11-28 22:46 UTC, anasolcentur commented
cambie el nombre, si. lo tengo que volver a Carrito?

2024-11-28 22:49 UTC, MVelasquez98 commented
Si, cuando es una clase es con PascalCase, primero mayuscula.
Por eso te da 404 not found, fijate el import
<img width="386" alt="image" src="https://github.com/user-attachments/assets/48c6ec8d-b6c3-48da-9f76-4b5476390278">
Estas importando un archivo que tiene otro nombre

2024-11-28 23:00 UTC, anasolcentur commented
Ahi esta solucionado.

@MVelasquez98

2024-11-28 23:02 UTC, MVelasquez98 requested changes
Sigue dando errores en consola, revisar comentarios. Siempre revisa la consola, click derecho inspeccionar
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/a9488003-1106-4727-90b8-0bb9663f5989">

2024-11-28 23:02 UTC, MVelasquez98 commented on script.js
> +import { Carrito } from './carrito.js';
Te va seguir dando 404, el archivo se llama Carrito.js, no hacia falta cambiar aca
<img width="324" alt="image" src="https://github.com/user-attachments/assets/6ecd61a9-2df3-43e6-8828-c6c15186dbd2">

2024-11-28 23:02 UTC, MVelasquez98 commented on script.js
> +import { Producto } from './producto.js';
Te va seguir dando 404, el archivo se llama Producto.js, no hacia falta cambiar aca
<img width="324" alt="image" src="https://github.com/user-attachments/assets/77734a30-ef2b-4b69-b74e-7f766d94ef41">

2024-11-28 23:21 UTC, anasolcentur commented
@MVelasquez98

2024-11-29 00:16 UTC, MVelasquez98 approved these changes
LGTM
Pensar en implementar en la otra entrega, algo para eliminar productos individuales del carrito, o aumentar o disminuir unidades
<img width="307" alt="image" src="https://github.com/user-attachments/assets/79116301-5e03-43ac-889d-6d69008477e4">

2024-11-29 01:36 UTC, merged